# Generated by Django 2.2.6 on 2019-12-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='position',
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Department'),
        ),
    ]
