# Generated by Django 2.2.6 on 2019-10-06 18:33

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 6, 18, 33, 51, 14729, tzinfo=utc), verbose_name='Created at')),
                ('type', models.CharField(choices=[('student', 'Student job'), ('iifo', 'IIFO job'), ('magistracy', 'Magistracy and graduates job'), ('learning_metodical', 'Learning metodical job'), ('organize_metodical', 'Organize metodical job'), ('scientific', 'Scientific job'), ('other', 'Other job')], max_length=64, verbose_name='Job type')),
                ('common_id', models.CharField(max_length=32, verbose_name='Number')),
                ('description', models.TextField(verbose_name='Job type')),
                ('dimension', models.CharField(max_length=256, verbose_name='Relate to')),
                ('factor', models.FloatField(verbose_name='Factor')),
                ('additional_load_method', models.CharField(blank=True, max_length=256, null=True)),
                ('additional_value', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, max_length=5, size=None)),
                ('validator_methods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, max_length=5, size=None)),
                ('validator_values', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, max_length=5, size=None)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
