# Generated by Django 2.2.6 on 2019-10-08 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Discipline name')),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 8, 18, 28, 5, 432667, tzinfo=utc), verbose_name='Created at'),
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_value', models.FloatField(verbose_name='Input value')),
                ('result_value', models.FloatField(verbose_name='Input value')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='central.Discipline')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='central.Job')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authapp.Teacher')),
            ],
            options={
                'verbose_name': 'Load',
                'verbose_name_plural': 'Loads',
            },
        ),
    ]
