# Generated by Django 2.2.6 on 2019-10-13 10:03

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_auto_20191011_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='semesters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, max_length=5, size=None),
        ),
        migrations.AddField(
            model_name='job',
            name='lesson_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('practice', 'Practice'), ('seminar', 'Seminar')], default='lecture', max_length=64, verbose_name='Lesson type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 13, 10, 2, 35, 366757, tzinfo=utc), verbose_name='Created at'),
        ),
    ]
