# Generated by Django 2.2.6 on 2019-11-07 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0004_auto_20191013_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='type',
        ),
        migrations.AddField(
            model_name='job',
            name='section',
            field=models.CharField(choices=[('student', 'Student job'), ('iifo', 'IIFO job'), ('magistracy', 'Magistracy and graduates job'), ('learning_metodical', 'Learning metodical job'), ('organize_metodical', 'Organize metodical job'), ('scientific', 'Scientific job'), ('other', 'Other job')], default='other', max_length=64, verbose_name='Job section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 19, 17, 53, 929639, tzinfo=utc), verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
