# Generated by Django 2.2.6 on 2019-12-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0005_auto_20191107_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='load',
            name='result_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Input value'),
        ),
    ]
