# Generated by Django 2.2.6 on 2019-12-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0006_auto_20191201_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='additional_value',
        ),
        migrations.AddField(
            model_name='job',
            name='additional_method_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
