# Generated by Django 2.2.6 on 2020-02-28 19:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0008_auto_20200218_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='semesters',
        ),
        migrations.AddField(
            model_name='discipline',
            name='semester',
            field=models.IntegerField(default=None, verbose_name='Semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='lesson_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('practice', 'Practice'), ('seminar', 'Seminar'), ('lab', 'Laboratory class'), ('credit', 'Credit'), ('exam', 'Exam'), ('consultation', 'Consultation'), ('check', 'Check'), ('dissertation', 'Dissertation'), ('other', 'Other')], max_length=64, verbose_name='Lesson type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='validator_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, max_length=5, size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='validator_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, max_length=5, size=None),
        ),
    ]
