# Generated by Django 2.2.6 on 2020-02-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0009_auto_20200228_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='additional_load_method',
            field=models.CharField(blank=True, choices=[('add_value', 'Add value'), ('substr_value', 'Subtract value')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='lesson_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('practice', 'Practice'), ('seminar', 'Seminar'), ('lab', 'Laboratory class'), ('credit', 'Credit'), ('exam', 'Exam'), ('consultation', 'Consultation'), ('check', 'Check'), ('dissertation', 'Dissertation'), ('heading', 'Heading'), ('other', 'Other'), ('prepare', 'Prepare')], max_length=64, verbose_name='Lesson type'),
        ),
    ]
