# Generated by Django 2.2.6 on 2020-03-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0011_auto_20200301_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='lesson_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Laboratory class'), ('practice_lessons', 'Practice lessons'), ('course_works', 'Course works'), ('consultation', 'Consultation'), ('credit', 'Credit'), ('exam', 'Exam'), ('magistracy', 'Magistracy'), ('review', 'Review'), ('other', 'Other')], max_length=64, verbose_name='Lesson type'),
        ),
    ]
