# Generated by Django 2.2.6 on 2020-03-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0012_auto_20200315_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='lesson_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Laboratory class'), ('practice_lessons', 'Practice lessons'), ('course_works', 'Course works'), ('consultation', 'Consultation'), ('credit', 'Credit'), ('exam', 'Exam'), ('magistracy', 'Magistracy'), ('review', 'Review'), ('diploma', 'Diploma heading'), ('gov_exam', 'Gov exam'), ('gec_diploma', 'GEC diploma'), ('practice', 'Practice'), ('other', 'Other')], max_length=64, verbose_name='Lesson type'),
        ),
    ]
